### ISSUE TITLE
Don't treat an auto-enabled enterprise roots setting as a heuristic to disable DoH

### ISSUE THREAD

**Issue by wthayer** [mozilla/doh-rollout#105]
@tdsmith pointed out that Firefox sometimes automatically enables enterprise roots when a MITM is detected. When that happens, it's probably not a good signal of an enterprise configuration (it's typically antivirus software), so it could cause us not to enable DoH for lots of users who would benefit from DoH (even if their device is intercepting their TLS connections locally). The recommendation is that we don't disable DoH when both `security.enterprise_roots.enabled` and `security.enterprise_roots.auto-enabled` are true (the latter indicates that enterprise roots was enabled due to our MITM detection logic).

**Comment by tdsmith** [comment]
The current behavior might be better -- we can't distinguish between Firefox-naïve antivirus MITM and Firefox-naïve enterprise middlebox configurations. If a middlebox MITM cert is deployed using e.g. Windows group policy without any accommodations for Firefox, it won't appear in the Firefox store, and any end user installing Firefox on their own will end up also relying on the auto-import behavior.

If we aren't sure how to distinguish AV and middleboxes, maybe we should leave things as they are for now.

**Comment by maxxcrawford** [comment]
Reverting this change until it can be tested/understood further.  Opened new issue/PR (#109) to revert this original commit. 

cc/ @nhi-nguyen

**Comment by maxxcrawford** [comment]
Bugzilla bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1605023
