### ISSUE TITLE
[Windows] The DoH add-on doesn't detect Parental Control on Windows

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/doh-rollout#107]
__[Affected versions]:__
- Firefox Release 69.0.1 (Build ID: 20190917135527)
- Firefox Nightly 71.0a1 (Build ID: 20190923215658)

__[Affected Platforms]:__
- All Windows

__[Prerequisites]:__
- Have a Windows Account with Child rights (Parental Control enabled).
- Have the latest [0.0.7 .xpi](https://bugzilla.mozilla.org/show_bug.cgi?id=1573840#c29) saved on your testing machine.

__[Steps to reproduce]:__
1. Open latest Firefox Release on your Child Account.
2. Install the DoH add-on Version 0.0.7 .xpi.
3. Navigate to the “about:config” page and set the `doh-rollout.enabled` preference to `true`.
4. Navigate to "about:telemetry" and observe the events.

__[Expected result]:__
- The "browserParent:disable_doh" event is displayed.

__[Actual result]:__
- The "browserParent:enable_doh" event is displayed.

__[Notes]:__
- This issue is not reproducible on macOS.
- In order to enable Parental Control, we used the instructions from the following link: https://famisafe.wondershare.com/parental-control/windows-10-parental-controls.html.

**Comment by maxxcrawford** [comment]
@SoftVision-CarmenFat I tried to set this up on a Windows 10 machine and wasn't able to get FF Parental Controls to work at all (Never even got to DoH testing step). I could only get parental controls to apply on MS Edge.

**Comment by SoftVision-CarmenFat** [comment]
I've also tested this with older versions (0.0.3, 0.0.5rc2 and 0.0.7), but the add-ons are not detecting  Parental Control either. 

Yes, Edge or Internet Explorer are the only browsers that can block websites, but after logging in the Parent's Account, we noticed that a list with all websites accessed while using Firefox browser is generated. I think there might be a Firefox issue since is not able to detect the Parental Control filters.

**Comment by maxxcrawford** [comment]
Okay – Can you confirm this further? We need to be sure Firefox can detect Windows 10 Parental Controls before DoH can be enable/disabled. I was unable to do it on my test machine.

**Comment by nhi-nguyen** [comment]
@SoftVision-CarmenFat To add to what Maxx said above, please confirm that, after setting parental controls in Windows, Firefox will send "Prefer:Safe" in the request headers when accessing any website. (See [here](https://stackoverflow.com/questions/33974595/in-firefox-how-do-i-see-http-request-headers-where-in-web-console) for how to see request headers)

**Comment by SoftVision-CarmenFat** [comment]
Retested this scenario using the latest Nightly build (Build ID: 20190925215653) but was unable to find any  "Prefer:Safe" in the request headers.

The reason I've used Nightly is because the code for detecting Parental Control has already landed there for a while as per bug [1570732](https://bugzilla.mozilla.org/show_bug.cgi?id=1570732).

I've navigated to several websites and verified if "Prefer:Safe" is displayed in the Network tab -> Headers, but I wasn't able to see any it in the Request Headers section. I also installed the ["HTTP HEADER Live"](https://addons.mozilla.org/ro/firefox/addon/http-header-live/) extension, but this didn't help either in finding the "Prefer:Safe".

![picturemessage_aelykjba ann](https://user-images.githubusercontent.com/26000308/65696007-2fde1f80-e081-11e9-8120-03ce8df6628e.png)

**Comment by maxxcrawford** [comment]
@SoftVision-CarmenFat So does that mean that Windows 10 Firefox is unable to detect/respond to parental controls? Specifically, where the `parentalControlsEnabled` pref returns true if parental controls are on? That is what the addon is testing for: 

+ Add-on reference: https://github.com/mozilla/doh-rollout/blob/master/src/experiments/heuristics/api.js#L72-L78
+ Searchfox ref: https://searchfox.org/mozilla-central/source/toolkit/components/parentalcontrols/nsIParentalControlsService.idl#47

**Comment by Softvision-PatriciuPop** [comment]
@maxxcrawford  I retested this and it turns out that Firefox has an issue detecting Parental Controls on Windows 10. On Windows 10 x64 I found the "Prefer:Safe" request header on Microsoft Edge but not on Firefox. On Windows 8.1 and 7 "Prefer:Safe" is present on Firefox as well.

**Comment by maxxcrawford** [comment]
Did the build work on W7 and 8?

**Comment by Softvision-PatriciuPop** [comment]
Yes, I just checked with the add-on installed and the "disable_doh" event with "browserParent:disable_doh" is displayed.

**Comment by nhi-nguyen** [comment]
Windows 10 platform bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1584613

**Comment by maxxcrawford** [comment]
Confirmed this worked as expected in Nightly on Windows 10! (Using build v0.0.11rc1)

**Comment by maxxcrawford** [comment]
Please test with https://github.com/mozilla/doh-rollout/releases/tag/0.0.11

**Comment by SoftVision-CarmenFat** [comment]
- We have tested using the latest version of the add-on 0.0.11 and can also confirm that it works as expected.
- Parental Control is now detected and generates the "browserParent:disable_doh" event.
- Tested this on Windows 10 x64 across channels: Release 69.0.2, Beta 70.0b11 and latest Nightly 71.0a1.
