### ISSUE TITLE
Do not see doorhanger and traffic still going through OS

### ISSUE THREAD

**Issue by kontrolldkaos** [mozilla/doh-rollout#112]
Trying this with 0.0.7.

Steps on Mac:
- Ensure that network.trr.mode is '0'
- Ensure that enterprise root security is 0
- Ensure that I am not using a resolver that NXDOMAIN's canary domain
- Clear all cookies
- Install the xpi
- Try to surf. All traffic still going through OS DNS. 
- Trigger Network restart. Still nothing.

**Comment by maxxcrawford** [comment]
@kontrolldkaos Did you add the pref per the README: 
> To see the banner create a new boolean pref doh-rollout.enabled in about:config and set to true.

The add-on does nothing currently without that pref being created/set. 

Which version of Firefox are you using?

**Comment by kontrolldkaos** [comment]
I am using 69.0.1. I will add that and see if it works. Though traffic is still going through OS.

**Comment by kontrolldkaos** [comment]
Okay, I now see the doorhanger. Another issue that I am seeing is that if/when I enable protected browsing or NXDOMAIN DNS servers, I can get my blocked domains, but traffic is still going through the DOH server first and subsequently for anything that is not blocked. Doesn't seem that it's completely disabling DOH, as what I would expect.

**Comment by kontrolldkaos** [comment]
I am able to get DoH disabled if I turn off and turn back on my network. A change of the DNS records does not constitute as a network event, as it should.

**Comment by kontrolldkaos** [comment]
Also confirm that if I close/open Firefox, after a DNS change only, trr mode does not change.

**Comment by kontrolldkaos** [comment]
I can close this as far as the Doorhanger issue seems to be resolved.
