### ISSUE TITLE
[Regression] The doorhanger is no longer displayed when focusing another tab and switching back

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/doh-rollout#114]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Nightly 71.0a1, Build ID 20190926094200
- Firefox Dev Edition 70.0b9, Build ID 20190923154733
- Firefox unbranded Release 69.0, Build ID 20190827005903

[Prerequisites]:
- The doh-rollout@mozilla.org-0.0.8-signed-testing.xpi add-on is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:config".
2. Add the "doh-rollout.enabled" boolean pref with the "true" value.
3. Focus another tab.
4. Switch back to the previous tab and observe the behavior.

[Expected result]:
- The DoH doorhanger notification is displayed.

[Actual result]:
- The DoH doorhanger notification is no longer displayed.

[Notes]:
- The issue is not reproducible using the 0.0.6 version of the add-on.
- The "enable_doh" telemetry event is sent and the "network.trr.mode" pref is set to "2".
- I have attached a screen recording of the issue:
![no_doorhanger](https://user-images.githubusercontent.com/40393891/65695694-ae868d00-e080-11e9-92aa-fa6fcf5c4e7e.gif)

**Comment by maxxcrawford** [comment]
This is as intended and a consequence of using the doorhanger UI and fixing #84. Specifically, if we want to trigger a closed tab as an "okay", the same event is also triggered when switching between two active tabs. (Reference to specific logic: https://github.com/mozilla/doh-rollout/blob/master/src/experiments/doorhanger/api.js#L61-L70)

@nhi-nguyen Can you confirm that this is acceptable?

**Comment by kontrolldkaos** [comment]
I'd like to add to this, when clicking Learn More in that doorhanger, it switches tabs and enables doh without user interaction of clicking Okay, I got it or Disable.

**Comment by kontrolldkaos** [comment]
I can also close the browser without interacting with Ok, Got it and doh is enabled when I start my browser back up.

**Comment by maxxcrawford** [comment]
@kontrolldkaos Closing the browser and having it enabled is the expected result.

@nhi-nguyen Considering the Learn More click, that again is a side-effect of fixing #84.

**Comment by nhi-nguyen** [comment]
Discussed out of band. This is a blocking issue.

**Comment by maxxcrawford** [comment]
We'll include excepted behavior and testing steps in the PR!  This should not require #84 to be re-opened, either!

**Comment by maxxcrawford** [comment]
@Softvision-PatriciuPop Please verify with https://github.com/mozilla/doh-rollout/releases/tag/0.0.9rc1

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using the doh-rollout@mozilla.org-0.0.9-rc1-signed.xpi add-on. Tested using Firefox Release 69, Beta 70 and Nightly 71 on Windows 10 x64.
