### ISSUE TITLE
"network.trr.mode" is wrongly set to "2" when creating the "doh-rollout.enabled" pref

### ISSUE THREAD

**Issue by heres-maria** [mozilla/doh-rollout#136]
[Affected Platforms]:

- All Windows

[Affected Versions]:

- Firefox Release 69.0.2,  Build ID  20191001234643
- Firefox Beta 70.0b12,  Build ID  20191002212950
- Firefox Nightly 71.0a1,  Build ID  20191006214844

[Prerequisites]:
  
- The doh-rollout@mozilla.org-0.0.11-signed.xpi add-on is installed.

[Steps to reproduce]:

  1.  Open the browser with the profile from prerequisites and navigate to "about:config".
  2.  Add the "doh-rollout.enabled" boolean pref with the "true" value.
  3.  Look at the "network.trr.mode" pref.
  
[Expected result]:

- The value of "network.trr.mode" is set to "0".

[Actual result]:

- The value of "network.trr.mode" is set to "2".

[Notes]:

- If the window is closed and then reopened, the notification doorhanger is displayed after interacting with the newly opened page (e.g. clicking on it).
- The issue is reproducible starting with the 0.0.9rc1 version of the add-on.
- I have attached a screen recording of the issue:
![network trr mode](https://user-images.githubusercontent.com/53752296/66299129-96720180-e8fb-11e9-8314-033d7b258385.gif)

**Comment by maxxcrawford** [comment]
This is actually an expected result now – we had an overall shift in heuristics, to where when the add-on is added/toggle on with the doh-rollout.enabled pref, it runs heuristics and flips to yes automatically. The only time doesn’t flip, is on user-choice/heuristics detection/policy setup.

As the initial goal is for the DoH Rollout to be a “opt-out” add-on, this change aligns more with that. 

@nhi-nguyen Thoughts?

**Comment by nhi-nguyen** [comment]
@heres-maria It's not clear to me what the issue is. If you're saying the issue is that, `network.trr.mode` should be 0 until user clicks on the OK button, then it is not an issue. It is working as expected (opt-out behaviour).

**Comment by SoftVision-CarmenFat** [comment]
@nhi-nguyen thanks for the clarification. Giving that it's an opt out add-on, is the information from the Notes section of the report also expected? I'm reffering to the fact that the notification doorhanger will be displayed again after restarting the browser and interracting with the page.

If this is also expected, then this report can be closed.

**Comment by SoftVision-CarmenFat** [comment]
Great! In this case, I'll have @heres-maria close the report.

Thank you.
