### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/doh-rollout#140]
References: 
- https://github.com/mozilla/example-addon-repo/blob/master/test/functional/button_test.js
- https://github.com/mozilla/contain-facebook/tree/master/test/features 
- https://github.com/mozilla/multi-account-containers/tree/master/test

**Comment by johannhof** [comment]
FYI, the FastBlock Shield study had an extensive set of tests that are also running on CI: https://github.com/mozilla/FastBlockShield/tree/master/test

**Comment by nhi-nguyen** [comment]
WONTFIX for this repo. Will be address in m-c version.
