### ISSUE TITLE
Do not run heuristics on network change if network ID is unchanged

### ISSUE THREAD

**Issue by nhi-nguyen** [mozilla/doh-rollout#145]
We should remember the network ID, and on connection change, check to see if the current network ID is different from the previous one, and only run heuristics if they are.

Exception: when network id is empty, we always run heuristics, because it could be the case when platform fails to reliably calculate a network id.

API: https://bugzilla.mozilla.org/show_bug.cgi?id=1550605

**Comment by maxxcrawford** [comment]
Bugzilla bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1605020
