### ISSUE TITLE
DoH is re-enabled after disabling it from "about:preferences" and restarting the browser 3 times

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/doh-rollout#152]
**[Notes]:**
- This issue is only reproducible with the latest `doh_roll-out-1.0.2-signed.xpi` build.
- This is also reproducible using Firefox Release 70.0.
- This issue is reproducible using the provided Normandy recipe via Normandy Devtools as well as using a recipe from the Stage environment.
- This issue is reproducible with both **"default"** and **"user"** preference types.

**[Affected versions]:**
- Firefox Release 69.0.3 (Build ID: 20191009172106)

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- The 1.0.2 add-on is installed.
- The `doh-rollout.enabled` pref is set as `true` by a Normandy recipe. 

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites.
2. Click the "OK, Got It" option from the notification.
3. Navigate to "about:preferences#general" - Network Settings section.
4. Click the "Settings" button.
5. Uncheck the "Enable DNS Over HTTPS" checkbox.
6. Click the "OK" button.
7. Close and open the browser 3 times.
8. Navigate to "about:config" page and observe the value of the "network.trr.mode" pref.

**[Expected result]:**
- The value of the pref is "0".

**[Actual result]:**
- The value of the pref is "2" and the DoH notification is displayed again.

**[Additional Notes]:**
- Please see the attached video:

![dns](https://user-images.githubusercontent.com/26000308/67688336-5950da80-f9a2-11e9-9bb9-01d983646bf4.gif)

**Comment by maxxcrawford** [comment]
Does this happen only on the third time? Or does it happen after the first as well?

**Comment by SoftVision-CarmenFat** [comment]
This only happens after closing and opening the browser the third time. The first 2 times, the "network.trr.mode" is set to "0" and respects the user's choice.

**Comment by nhi-nguyen** [comment]
@SoftVision-CarmenFat please reopen this if it still occur in the latest version.

**Comment by SoftVision-CarmenFat** [comment]
- I have verified this issue using the latest 1.0.3 build from the test channel and can confirm that it's not reproducible anymore.
- The user's choice to disable DNS via "about:preferences" page is respected and remains the same after restarting the browser several times.
