### ISSUE TITLE
DoH is wrongly disabled after restarting the browser if it was previously disabled and re-enabled from the "about:preferences" page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/doh-rollout#156]
**[Affected versions]:**
- Firefox Release 69.0.3 (Build ID: 20191009172106)

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- The 1.0.3 add-on is installed.
- The "doh-rollout.enabled" pref is set as true by a Normandy recipe. 

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites.
2. Click the "OK, Got It" option from the notification.
3. Navigate to "about:preferences#general" - Network Settings section.
4. Click the "Settings" button and _**uncheck**_ the "Enable DNS Over HTTPS" checkbox.
5. Click the "OK" button and restart the browser.
6. Navigate to "about:preferences#general" - Network Settings section.
7. Click the "Settings" button and _**check**_ the "Enable DNS Over HTTPS" checkbox.
8. Click the "OK" button and restart the browser.
9. Navigate to "about:config" page and observe the value of the "network.trr.mode" pref.

**[Expected result]:**
- The value of the pref is "2".

**[Actual result]:**
- The value of the pref is "0".

**[Additional Notes]:**
- Please see the attached video:

![reenable dns](https://user-images.githubusercontent.com/26000308/67774277-beb9cf80-fa65-11e9-86aa-96c3433ecf86.gif)

**Comment by maxxcrawford** [comment]
@SoftVision-CarmenFat Can you verify that the initial Normandy pref is getting set during the restart steps? From your video, it looks like it's only being set on the first start up and not on the subsequent restarts.

**Comment by maxxcrawford** [comment]
Additionally, can you also show any telemetry events (about:telemetry#events) between after setting the pref, on each restart? That will show if the addon is responsible for the changes.
