### ISSUE TITLE
Revised Doorhanger UI

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/doh-rollout#158]
We still need someone from the UX team to drive this, but changes include: 

- Updated icon
- Updated placement
- Revised copy
- Revised typography
  - Better spacing control between headline and body copy

**Comment by cfogelSV** [comment]
Currently encountered issues:
* the description for the feature/addon is continued, on the same row as title
** not title on 1 row, spacing, description);
* tab_Index should be revised for [Disable] and [Ok, Got it] buttons. 
** macOS is left->right vs Windows/Ubuntu right->left which wouldn't be normally expected;

Will add more, if uncovered during testing.

**Comment by nhi-nguyen** [comment]
cc @nhnt11 FYI, see comment above.

WONTFIX for this version.

**Comment by maxxcrawford** [comment]
Bugzilla bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1605022
