### ISSUE TITLE
Confirm Mac/Linux OS Support 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/doh-rollout#159]
Test the add-on in both: 
- Mac OS
- Linux OS

**Comment by maxxcrawford** [comment]
@nhi-nguyen I don't think this issue needs to be ported, as its' already covered in the PI request for v1.3. Let me know and I can file it. 

If so, should it be two bugs, one for each OS?

**Comment by nhi-nguyen** [comment]
no need to port this issue (it's a non-issue)
