### ISSUE TITLE
de-dup network change api

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/doh-rollout#167]
https://github.com/mozilla/doh-rollout/blob/8ffa1ad1f6123621bf6cb7e6ca356e8139e2654e/src/experiments/netChange/api.js#L29

What specifically about the networkStatus API cannot work for the doh-rollout?

https://searchfox.org/mozilla-central/source/toolkit/components/extensions/parent/ext-networkStatus.js

If there are problems with the implementation available I'd like to see some bugzilla bugs with details so we can address them.

**Comment by nhi-nguyen** [comment]
IIRC, the networkStatus API landed in 70. We needed something that worked on 69 as well.

**Comment by mixedpuppy** [comment]
That explains a lot.  I'm still curious about the differences in the implementation.  If the m-c implementation had been available, is it sufficient or do we need to make changes?

**Comment by nhi-nguyen** [comment]
cc @nhnt11

**Comment by maxxcrawford** [comment]
This has been resolved in-tree. @nhnt11 Can you confirm?

**Comment by nhnt11** [comment]
Yup, resolved in m-c.
