### ISSUE TITLE
remove use of ExtensionPreferencesManager

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/doh-rollout#168]
https://github.com/mozilla/doh-rollout/blob/8ffa1ad1f6123621bf6cb7e6ca356e8139e2654e/src/experiments/preferences/api.js#L18

Given my understanding, the intention is that after uninstall the DOH preferences set are left in place.  The safest bet at this point is to do that directly rather than through the ExtensionPreferencesManager.  Once a number of bugs are addressed, it is unlikely to work in a way that will fulfill the use case here.

**Comment by mixedpuppy** [comment]
If you specifically need to know that secure proxy has set the prefs, you could check doing something like:

```
await ExtensionSettingsStore.initialize();
let control = await ExtensionSettingsStore.getLevelOfControl(
  "secure-proxy@mozilla.com", "prefs", "secureProxy.DNSoverHTTP");
return control === "controlled_by_this_extension";
```

But if you want to avoid stepping on anything, just checking for a user-set pref for mode would probably do it.

**Comment by maxxcrawford** [comment]
This has already been removed. @nhnt11 Can you confirm?

**Comment by nhnt11** [comment]
Yeah, we're not using EPM anymore.
