### ISSUE TITLE
Add remote update pref 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/doh-rollout#178]
Watch/listen for pref that if detected can do one of the following: 
- Leave `network.trr.mode` setting as is and disable heuristics 
- Set all `network.trr.mode` users with value of `2` to `0` and disable heuristics 
- Set all `network.trr.mode` users with value of `0` to `2` and disable heuristics 
 
_Note: Any user with a `network.trr.mode` of `3` or `5` would not be targeted. Additionally, heuristics will already be disabled for them._

```
// Pref that will clean up after the add-on in case of emergency.
const DOH_REMOTE_DISABLE_PREF = "doh-rollout.remote-disable";
```

**Comment by nhi-nguyen** [comment]
@maxxcrawford what's the status of this issue?

**Comment by maxxcrawford** [comment]
No progress on this has been made. This was stalled during the transition to v1.3/in-tree. I recommend migrating the bug to Bugzilla. Want me to do that?

**Comment by nhi-nguyen** [comment]
@maxxcrawford yes please and close this bug when that's done.

**Comment by maxxcrawford** [comment]
Bugzilla bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1605014
