### ISSUE TITLE
Make pref names more readable 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/doh-rollout#179]
Note that this is a rather confusing name, since it seems to mean "DoH is disabled" but conflicts with the more generic 'addon is disabled'

_Originally posted by @nhnt11 in https://github.com/mozilla/doh-rollout/pull/164_

**Comment by nhi-nguyen** [comment]
WONTFIX in this version. Any fixes done will be in the in tree version.

**Comment by maxxcrawford** [comment]
Bugzilla bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1605013
