### ISSUE TITLE
The "doh-rollout.self-enabled" pref remains set to true even after removing the add-on

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/doh-rollout#183]
**[Affected Platforms]:**
- All Windows

**[Affected Versions]:**
- Firefox Release 70.0.1, Build ID 20191030021342
 
**[Prerequisites]:**
- Have the latest [1.1.0rc1](https://github.com/mozilla/doh-rollout/releases) add-on saved on your machine.

**[Steps to reproduce]:**
1. Open the browser with a new profile.
2. Install the add-on.
3. Add the "doh-rollout.enabled" pref with the "true" value.
4. Click the "Ok, Got it" button from the doorhanger.
5. Navigate to "about:support" and open the Profile folder.
6. Close the browser.
7. Go to "Extensions" subfolder and delete the "doh-rollout@mozilla.org.xpi" add-on.
8. Reopen the browser and navigate to "about:config" page.
9. Observe if the "doh-rollout.self-enabled" pref is set to false.

**[Expected result]:**
- The "doh-rollout.self-enabled" pref is set to false.

**[Actual result]:**
- The "doh-rollout.self-enabled" pref remains set to true.

**[Notes]:**
- According to this [documentation](https://github.com/mozilla/doh-rollout/pull/164), "If DoH is disabled, this is flipped to false".
- This is also reproducible with installing the add-on as temporary.
- I have attached a screen recording of the issue:

![pref](https://user-images.githubusercontent.com/26000308/68780899-a1792980-063f-11ea-9680-7daec972e7e7.gif)

**Comment by maxxcrawford** [comment]
This is expected behavior. Specifically, all the prefs set by this add-on should remain after uninstall. 

- `doh-rollout.enabled`
- `doh-rollout.self-enabled`
- `doh-rollout.previous.trr.mode`
- `doh-rollout.doorhanger-shown`
- `doh-rollout.doorhanger-decision`
- `doh-rollout.disable-heuristics`

**Comment by maxxcrawford** [comment]
@nhi-nguyen Thoughts?

**Comment by SoftVision-CarmenFat** [comment]
This is confusing since you just mentioned this in the previous email:
_"The only time the doh-rollout.self-enabled pref should be removed is when the user manually updates their TRR.MODE via about:preferences#networking or by clicking "Disable" on the doorhanger."_

**Comment by maxxcrawford** [comment]
Specifically, removing the add-on doesn't trigger either of those events.
