### ISSUE TITLE
The "doh-rollout.self-enabled" pref is not removed after changing the "network.trr.mode" pref value via “about:preferences#networking” page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/doh-rollout#184]
**[Affected Platforms]:**
- All Windows

**[Affected Versions]:**
- Firefox Release 70.0.1, Build ID 20191030021342
 
**[Prerequisites]:**
- Have an active Normandy [testing recipe ](https://delivery-console.stage.mozaws.net/recipe/878/)for DoH.
- You are enrolled in the Treatment branch.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:preferences#networking" page.
3. Click the "Settings" button and uncheck the "Enable DNS over HTTPS" checkbox.
4. Click the "OK" button.
5. Restart the browser.
6. Observe if the "doh-rollout.self-enabled" preference is removed.

**[Expected result]:**
- The "doh-rollout.self-enabled" pref is removed.

**[Actual result]:**
- The "doh-rollout.self-enabled" pref is displayed.

**[Notes]:**
- The issue is not reproducible when the user chooses to opt-out from the experiment through the DoH doorhanger.
- I have attached a screen recording of the issue:

![self pref](https://user-images.githubusercontent.com/26000308/68857448-75b37d80-06eb-11ea-80c8-2392971be0d2.gif)

**Comment by maxxcrawford** [comment]
This pref is cleared on the SECOND restart after user disabling DoH manually. This add-on only fires its main function (and makes changes) retroactively after Start Up/Network Change/`doh-rollout.enabled` pref update. 

To make this more transparent, I've written out the chain of events that happen what a user manually disables DoH (via about:preferences), including expected prefs that should update/remain the same. Note that there are additional prefs being set (all under the `doh-rollout.` namespace) but the prefs outlined below are the ones that should be checked in this test case. 

**Step 1: First Run** 
_Start with a clean profile. Run add-on however you prefer. (Via flipping `doh-rollout.enabled` pref, or Normandy study.)_ 

Expected Prefs: 
- `doh-rollout.self-enabled`: true
- `doh-rollout.disable-heuristics`: Should not exist
- `network.trr.mode`: 2

**Step 2: Update DoH via about:preferences** 
_When a user unchecks DoH in about:preferences#networking, this triggers NO actions by the add-on immediately. The add-on only runs on browser startup, network change event (note the 60s timeout here) or when the `doh-rollout.enabled` pref is updated. 

Expected Prefs: 
- `doh-rollout.self-enabled`: true
- `doh-rollout.disable-heuristics`: Should not exist
- `network.trr.mode`: 0

**Step 3: Restart/Network Change** 
_Addon detects that user pref has changed for `network.trr.mode`. Heuristics will be disabled and DoH is NOT enabled._ 

Expected Prefs:
- `doh-rollout.self-enabled`: true
- `doh-rollout.disable-heuristics`: true
- `network.trr.mode`: 0

**Step 4: Restart/Network Change**
The add-on is now in its [final disable loop](https://github.com/mozilla/doh-rollout/blob/master/src/background.js#L464-L471), detecting/catching the `doh-rollout.disable-heuristics` pref. This logic will clear the `doh-rollout.self-enabled` pref and not run heuristics.

Expected Prefs:
- `doh-rollout.self-enabled`: Should not exist
- `doh-rollout.disable-heuristics`: true
- `network.trr.mode`: 0

**Comment by maxxcrawford** [comment]
However, I think we could safely clear this pref whenever `rememberDisableHeuristics()` is ran, to make the pref removed faster.
