### ISSUE TITLE
Enabling DNS-over-HTTPS with a custom provider results in all attempts to load that provider origin being directed to 1.1.1.1

### ISSUE THREAD

**Issue by DoctorMcKay** [mozilla/doh-rollout#192]
[Originally posted on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1598254)

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

Tested with Firefox Developer Edition 71.0b11.

1. Tick the "Enable DNS over HTTPS" box in network/connection settings
2. In the "Use provider" box, select "Custom"
3. Enter https://www.example.com in the "Custom" text box
4. Attempt to visit https://www.example.com

Upon attempting to visit https://www.example.com, a certificate error is encountered. If you click through it, you will land on a Cloudflare 403 page. In the network tab of the dev tools, notice that the remote address is 1.1.1.1:433.

**Comment by nhi-nguyen** [comment]
@DoctorMcKay Thanks for filing the bug on Bugzilla and here. We will process the bug on Bugzilla. Sorry for the confusion.
