### ISSUE TITLE
Disable Pocket policy is not seen as active after disconnecting and reconnecting to the network

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla/doh-rollout#194]
**[Affected Platforms]:**
- Windows 10x64
- Windows 7x64
- macOS 10.15
- Ubuntu 18.04x64

**[Affected Versions]:**
- Firefox Release 71.0
- Firefox Beta 71.0b12
- Firefox Nightly 72.0a1 (BuildID 20191127114233)

**[Prerequisites]:**
- Have an active Normandy testing [recipe](https://delivery-console.stage.mozaws.net/recipe/880/) for DoH.
- You are enrolled in the Treatment branch.
- Add the policies.json in the firefox/distribution folder with the following content:
{
  "policies": {
    "DisablePocket": true
  }
}

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Go to about:config and add *doh-rollout.enabled* to *true*.
3. Go to about:telemetry#events-tab.
4. **Disconnect** from network and **reconnect**.
5. Wait ~1min and refresh the about:telemetry#events-tab page.

**[Expected result]:**
- Doorhanger isn't displayed and telemetry event with **Value**  *policy_without_doh* is recevied.

**[Actual result]:**
- Doorhanger is displayed and telemetry event doesn't see the policie as enabled.

**[Notes]:**
- The issue is reproducible with the 1.2.0rc2 version of the add-on.
- I have attached a screenshot of the issue:
![Untitled1](https://user-images.githubusercontent.com/54393305/69737175-998bb000-113c-11ea-9195-ac6327e3abe2.png)

**Comment by nhnt11** [comment]
I can confirm that the existence of an enterprise policy that omits `DNSOverHTTPS` is not respected after a network change. (not just the pocket policy case)
