### ISSUE TITLE
Missing doorhanger and "netChange" telemetry when disconnecting and reconnecting to the network after changing the "DNSOverHTTPS" policy from false to true

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla/doh-rollout#197]
**[Affected Platforms]:**
- Windows 10x64
- Windows 7x64
- macOS 10.15
- Ubuntu 18.04x64

**[Affected Versions]:**
- Firefox Release 70.0.1
- Firefox Beta 71.0b12
- Firefox Nightly 72.0a1 (BuildID 20191127215655)

**[Prerequisites]:**
- Have an active Normandy testing [recipe](https://delivery-console.stage.mozaws.net/recipe/880/) for DoH.
- You are enrolled in the Treatment branch.
- Add the policies.json in the firefox/distribution folder with the following content:
{
"policies": {
"DNSOverHTTPS": {
"Enabled": true,
"ProviderURL": "https://mozilla.cloudflare-dns.com/dns-query",
"Locked": true
}
}
}

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Go to about:config and add *doh-rollout.enabled* to *true*.
3. Go to about:telemetry#events-tab.
4. **Disconnect** from network.
5.  Go to firefox/distribution and change the "DNSOverHTTPS" policy from *false* to *true*.
6. **Reconnect** to network.
7. Wait ~1min and refresh the about:telemetry#events-tab page.

**[Expected result]:**
- Doorhanger is displayed and telemetry event with **Value**  *netChange* is recevied.

**[Actual result]:**
- Doorhanger isn't displayed and no telemetry event with "netChange" is generated.

**[Notes]:**

- The issue is reproducible with the 1.2.0rc2 version of the add-on.
- Following the steps mentioned above but without network disabling and enabling, just changing the "DNSOverHTTPS" policy from false to true and restart Firefox, doorhanger is missing too. 
- I have attached a screen recording of the issue:
![DNS](https://user-images.githubusercontent.com/54393305/69793997-23398d00-11d2-11ea-9fb8-62b4fe536179.gif)

**Comment by maxxcrawford** [comment]
This is incorrect – if any policy is in place, the user should not see a door hanger, or have any heuristics ran period. This includes no telemetry for netChange events too.

**Comment by maxxcrawford** [comment]
cc @nhi-nguyen
