### ISSUE TITLE
Add-on will always enable itself if doh-rollout.previous.trr.mode doesn't exist

### ISSUE THREAD

**Issue by nhnt11** [mozilla/doh-rollout#199]
The add-on will not respect the value of the enabled pref or the study branch while checking whether to enable itself for new users ("new" in the sense that `doh-rollout.previous.trr.mode` is unset).

When fetching the value of this pref, we pass `0` as the default value if it doesn't exist [1], and later we check for a `0` value which will evaluate to `true` [2].

[1] https://github.com/mozilla/doh-rollout/blob/ec651685125bdf566c7ffd791d09aa3703990202/src/background.js#L547

[2] https://github.com/mozilla/doh-rollout/blob/ec651685125bdf566c7ffd791d09aa3703990202/src/background.js#L563

**Comment by nhi-nguyen** [comment]
This means that the addon will run for users in the control branch.

@mariaberlinger Once this issue is fixed and a new version is available for testing, please verify that the addon **doesn't run** for users in the control branch.

**Comment by mariaberlinger** [comment]
@nhi-nguyen  we were under the impression that this feature will be Rolled out. In this case, branches are not supported for the current addon-rollout action. Can you please confirm if v1.2 will be a Rollout or a Branched add-on experiment?

**Comment by maxxcrawford** [comment]
@mariaberlinger @nhi-nguyen v1.2 will be deployed via Normandy as a study/experiement. 

There is a separate task of migrating this add-on to Nightly/in-tree, where the actual rollout will happen.
