### ISSUE TITLE
Telemetry event shows "evaluateReason": "userModified" instead of "evaluateReason": "startup"

### ISSUE THREAD

**Issue by cbaica** [mozilla/doh-rollout#202]
**[Affected Platforms]:**
Windows 10x64
Windows 7x64
macOS 10.15
Ubuntu 18.04x64

**[Affected Versions]:**
Firefox Release 70.0.1
Firefox Beta 71.0b12
Firefox Nightly 72.0a1 

**[Prerequisites]:**
Have the DoH addon/recipe active and enabled (doh-rollout.enabled = true).

**[Steps to reproduce]:**
1. Open the browser, go to about:preferences, search for the "Network Settings" option and disable the "Dns over HTTPS" option.
2. Restart the browser (open console then CTRL+ALT+R).
3. Go to about:telemetry#events tab and investigate the dynamic event, the extra content column.

**[Expected result]:**
The evaluateReason value is listed as "startup".

**[Actual result]:**
The evaluateReason value is "userModified".

**[Notes]:**
The issue is reproducible with the 1.2.0rc2 version of the add-on.
![image](https://user-images.githubusercontent.com/51120799/69978347-f8826800-1534-11ea-8cdd-cd53c099cbaf.png)

**Comment by maxxcrawford** [comment]
This is expected — user modified means that the user has made a choice to enable/disable DoH separate from the add-on, and the add-on will be disabled. 

cc/ @nhi-nguyen

**Comment by maxxcrawford** [comment]
@nhi-nguyen Should this be ported over? I think this is expected behavior right now.

**Comment by nhi-nguyen** [comment]
@maxxcrawford we don't need to port this issue.
