### ISSUE TITLE
network.trr.mode=3 prevents the user from accessing any website after reconnecting to the network

### ISSUE THREAD

**Issue by dcicas** [mozilla/doh-rollout#205]
**Affected versions**
* Fx 70.0.1
  Fx 71.0b12

**Affected platforms**
* mac OS 
  Ubuntu 18.04
  Windows 10
  Windows 7

**Steps to reproduce**
Preconditions
The Doh add-on is installed and the network.trr.mode pref value is 2.
The "doh-rollout.enabled" boolean pref was added with the "true" value.

1. Disconnect from the network.
2. Navigate to the "about:config" page.
3. Navigate to the "about:config" page and change the network.trr.mode pref value to 3.
4. Reconnect to the network.
5. Navigate to the "about:config" page and observe the network.trr.mode pref value.

**Expected result**
* You are able to navigate the internet after reconnecting and setting trr to 3.

**Actual result**
* The pref stays at 3 but you can no longer visit websites.

I added a http log [here](https://drive.google.com/file/d/1FID8hxCTHHZ_aih6-Sv4BRslRCm8TZ55/view?usp=sharing)

**Comment by maxxcrawford** [comment]
Bug [filled on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1600976). Closing here.
