### ISSUE TITLE
The 1.3.0 in-tree add-on doesn't respect user's set policies

### ISSUE THREAD

**Issue by mariaberlinger** [mozilla/doh-rollout#212]
**[Affected Platforms]:**
- Windows 10x64
- Windows 7x64
- macOS 10.15
- Ubuntu 18.04x64

**[Affected Versions]:**
- Firefox Beta 72.0b5

**[Prerequisites]:**
- Add the policies.json in the firefox/distribution folder with the following content:
{
"policies": {
"DNSOverHTTPS": {
"Enabled": true,
"ProviderURL": "https://mozilla.cloudflare-dns.com/dns-query",
"Locked": true
}
}
}

Or

{
"policies": {
"DisablePocket": true
}
}
Or set from ADMX those policies for Windows. 

**[Steps to reproduce]:**
1. Open the browser.
2. Go to about:config and add *doh-rollout.enabled* to *true*.
3. Go to about:telemetry#events-tab.
4. Bring back in focus the about:config page.
5.  Wait ~1min.

**[Expected result]:**
- The "network.trr.mode" pref doesn't change its value.
- The DoH doorhanger is not displayed.

**[Actual result]:**
Here are a few scenarios depending on which policy was set:
1. If Pocket policy is set (via JSON or ADMX)
    a. The network.trr.mode pref is 0 and policy_without_doh telemetry is received.
    b. After ~1min the network.trr.mode is flipped to 2, doorhanger is displayed and enable_doh telemetry is received.
2. DNS policy is set to disable (via JSON or ADMX)
    a. The network.trr.mode pref is 5 and disable_doh telemetry is received.
    b. After ~1min the network.trr.mode is flipped to 0 and another disable_doh telemetry is received (**NOTE** if DNS policy is set by JSON and the network.trr.mode pref is locked, the value for network.trr.mode remains 5).
3. DNS policy is set to enable(via JSON or ADMX)
    a. The network.trr.mode pref is 2 and enable_doh telemetry is received.
    b. After ~1min the network.trr.mode is not flipped but another enable_doh telemetry is received and the DOH doorhanger is displayed (**NOTE** if DNS policy is set by JSON and the network.trr.mode pref is locked, the value for network.trr.mode remains 2).

**[Notes]:**
- The issue is reproducible with the 1.3.0 in-tree add-on.
- I have attached a screen recording of the issue:
![policies](https://user-images.githubusercontent.com/54393305/70725722-8e707c80-1d05-11ea-9cc7-a4a1abb49e71.gif)

**Comment by nhi-nguyen** [comment]
closing this issue. Bug tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1603478
