### ISSUE TITLE
Multiple "netChange" telemetry events are sent on Firefox 69

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/doh-rollout#72]
[Notes]:
- On Linux the behavior is different, after a network change, no telemetry events are displayed.

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Unbranded Release 69.0, Build ID 20190827005903
- Firefox Release 69.0, Build ID 20190827005903

[Prerequisites]:
- The doh-rollout@mozilla.org-0.0.5rc2-signed.xpi add-on is installed.
- Have the "doh-rollout.enabled" boolean pref set to "true".
- DoH is enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Disconnect and reconnect to the internet.
3. Navigate to about:telemetry and observe the events.

[Expected result]:
- One DoH heuristics event is displayed with the "evaluateReason:netChange" value.

[Actual result]:
- Multiple pings (2-3) are displayed.

[Additional Notes]:
- I have attached a screen recording of the issue:
![multiple_net](https://user-images.githubusercontent.com/40393891/64966346-475e2100-d8a7-11e9-89b0-e2855677e569.gif)

**Comment by Softvision-PatriciuPop** [comment]
I have retested this scenario with the doh-rollout@mozilla.org-0.0.7-signed.xpi add-on and the behavior has changed. Changing the network causes 2 telemetry events to appear, a “disable_doh” event with the "canary": "disable_doh" followed by a correct “enable_doh” event.
The Behavior is different across platforms and Firefox versions, as detailed in the table below:

| - | Windows 10 | macOS | Linux |
| ------------- | ------------- | ------------- | ------------- |
| Unbranded 69 | unaffected  | affected  | affected  |
| Release 69 | unaffected  | affected  | unaffected  |
| Beta 70 | No telemetry events  | affected  | affected  |
| Dev Edition 70 | No telemetry events  | affected  | affected  |
| Nightly 71 | unaffected  | affected  | affected  |
- Affected - 2 telemetry events (1 disable_doh, 1 enable_doh)
- Unaffected - 1 telemetry event (enable_doh)
- No telemetry events - No events are displayed when executing a netChange

**Comment by maxxcrawford** [comment]
@Softvision-PatriciuPop We have two PRs teed up to resolve these issues. We'll have a new cut signed for testing tomorrow your time! 

Related PRs:
- #103 
- #102

**Comment by nhi-nguyen** [comment]
@maxxcrawford: We should also address the issue of no telemetry events on 70.

**Comment by maxxcrawford** [comment]
@Softvision-PatriciuPop Can you verify this exists in https://github.com/mozilla/doh-rollout/releases/tag/0.0.8?

**Comment by maxxcrawford** [comment]
Verified that this version is working for me: [Screen recording](https://i.imgur.com/mYzqfG9.mp4) 

This is in the unsigned 69 version on Mac OSX. I only get one event, that DoH has been enabled after the network is back up.

**Comment by maxxcrawford** [comment]
@Softvision-PatriciuPop Can you verify the network changing in a few ways? 

- Change to an different WiFi network 
- Turn off network for 1 second, toggle back on
- Turn off network for 5 seconds, toggle back on
- Turn off network for 15 seconds, toggle back on

I'm curious if any of these return different results. Thanks!

**Comment by Softvision-PatriciuPop** [comment]
I have retested the steps mentioned above using the doh-rollout@mozilla.org-0.0.8-signed-testing.xpi add-on and the issue is still reproducible according to the following tables:

**Windows:**

| - | 1 second | 5 seconds | 15 seconds | Different Wifi 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Unbranded 69 | unaffected | unaffected | unaffected | unaffected |
| Dev Edition 70 | No telemetry events | No telemetry events | No telemetry events | No telemetry events |
| Nightly 71 | No telemetry events | No telemetry events | No telemetry events | No telemetry events |

**Mac:**

| - | 1 second | 5 seconds | 15 seconds | Different Wifi 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Unbranded 69 | unaffected | affected | unaffected | unaffected |
| Dev Edition 70 | affected | affected | affected | unaffected |
| Nightly 71 | affected | affected | affected | unaffected |

**Linux:**

| - | 1 second | 5 seconds | 15 seconds | Different Wifi 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Unbranded 69 | unaffected | unaffected | unaffected | unaffected |
| Dev Edition 70 | No telemetry events | enable/disable | enable/disable | unaffected |
| Nightly 71 | unaffected | unaffected | unaffected | unaffected |
- On Linux Dev Edition 70 reconnecting after 5 and 15 seconds seconds displays a single enable_doh or disable_doh event.

**Comment by valenting** [comment]
The Windows issue is being handled in bug [1583170](https://bugzil.la/1583170)

**Comment by nhi-nguyen** [comment]
@maxxcrawford Please look into the case of Unbranded 69/5 second on MacOS in [Patriciu's comment](https://github.com/mozilla/doh-rollout/issues/72#issuecomment-535063230) above.

**Comment by maxxcrawford** [comment]
Re-opening this will until @Softvision-PatriciuPop verifies.

**Comment by SoftVision-CarmenFat** [comment]
- Tested this using the latest version of the add-on 0.0.10 and I am not able to see any "netChange" telemetry events at all.
- I have verified this scenario on Windows 10 x64 across channels: Release 69.0.1, Unbranded Release 69.0.1, Beta 70.0b11, and latest Nightly 71.0a1. 

![netChange Win](https://user-images.githubusercontent.com/26000308/66128395-6f16ee00-e5f6-11e9-9864-1af35fcfab2b.gif)

**Comment by maxxcrawford** [comment]
@SoftVision-CarmenFat The netChange event only sends the event after both the timeout finishes and it detects an up connection. Can you test one more time, and give it a few additionally seconds to refresh the about:telemetry page?

**Comment by SoftVision-CarmenFat** [comment]
I still don't get the "netChange" event even after waiting for about 15 seconds before refreshing the "about:telemetry" page. Should I wait for more time?

![nwt](https://user-images.githubusercontent.com/26000308/66140492-e5bde680-e60a-11e9-823e-eae4065865f9.gif)

**Comment by maxxcrawford** [comment]
@SoftVision-CarmenFat I filed an issue, #130 to resolve this. It'll be testable in the next release.

**Comment by maxxcrawford** [comment]
@SoftVision-CarmenFat @Softvision-PatriciuPop Please use the latest release - https://github.com/mozilla/doh-rollout/releases/tag/0.0.11. Note that this build is signed for full release, so do not use the pref, `xpinstall.signatures.dev-root`!

**Comment by SoftVision-CarmenFat** [comment]
@maxxcrawford 
- We have tested this scenario using the latest version of the add-on 0.0.11 and the issue is still reproducible on our side.
- Although we don't see the "canary": "disable_doh" event anymore, there are still 2 "netChange" events displayed after reconnecting to network.
- This is reproducible on Windows 10 x64 across channels: Release 69.0.2, Beta 70.0b11 and latest Nightly 71.0a1.

**Comment by maxxcrawford** [comment]
@SoftVision-CarmenFat @Softvision-PatriciuPop Revised the timeout to go back to 60s. Please be sure to wait for at least 60s after the network change to check for the dynamic telemtery event. Please verify with this version: @Softvision-PatriciuPop @SoftVision-CarmenFat Tested both edge cases with v0.0.12 – Please verify! https://github.com/mozilla/doh-rollout/releases/tag/0.0.12 Thanks!

**Comment by SoftVision-CarmenFat** [comment]
- Tested this using the latest 0.0.12 version of the add-on and the issue is no longer reproducible. 
- There is only one "netChange" event generated when reconnecting to the network.
- Tested on Window s10 x64 across channels: Release 60.0.2, Beta 70.0b12 and latest Nightly.
