### ISSUE TITLE
DoH not enabled after heuristics change

### ISSUE THREAD

**Issue by wthayer** [mozilla/doh-rollout#89]
Steps to reproduce:
1. Ensure that TRR mode is set to 0
2. Ensure that the Comcast canary will be triggered (for example, by adding an entry for test.xfiprotectedbrowsing.com to /etc/hosts)
2. Install 0.6 internal add-on (the one that doesn't require doh_rollout.enabled=true)

Result: no doorhanger as expected.

3. Remove settings that trigger the canary (for example, by removing /etc/hosts entry)
4. Turn network off and back on (note: I did this in two ways - rebooted my wireless router and turned WiFi off and back on on my Mac. Both produced the same result. It is possible that I simply failed to produce a "network change" event).

Result: still no doorhanger. Data in telemetry shows that all heuristics resulted in doh_enabled, but also  'doh state enabled null'.

5. Reinstall the add-on or restart the browser

Result: doorhanger immediately appears

Environment: macOS, Firefox Nightly and Release

**Comment by maxxcrawford** [comment]
@wthayer Can you re verify this issue? It may be disregarded now as it was related to the Comcast domain.

**Comment by nhi-nguyen** [comment]
Closing this as we no longer use Comcast domains.
