### ISSUE TITLE
Sync back Pontoon branch to master

### ISSUE THREAD

**Issue by flodolo** [mozilla/doh-rollout#92]
There is currently not trace of localization on master, while most of the languages are completely translated. Can we make sure the two branched are synced before shipping?

**Comment by flodolo** [comment]
On my side there's no plan to move Pontoon to master. This should be a one-off project, we might need to check in the future if there's more content to sync from that branch to master, but that's pretty much it.

**Comment by maxxcrawford** [comment]
Okay! All merged. Please let me know if we need to do this again before final roll-out next week.

**Comment by flodolo** [comment]
@maxxcrawford 
Looks like we got Russian and one update for zh-CN, if you have time to sync back.
