### ISSUE TITLE
Confirm all telemtery events fire correctly

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/doh-rollout#97]
Note - These events only apply to users who have not already enabled/disabled DoH before the add-on was added to their system. 

## Events
- On startup 
  - Include DoH status, heuristic results
- On network change 
  - Include DoH status, heuristic results

**Data sent:** 
On events, include the following: 
- DoH Status (enabled, disabled) 
- Heuristics  results
	- google
	- youtube
	- comcastProtect
	- comcastParent
	- canary
	- modifiedRoots
	- browserParent
	- thirdPartyRoots
	- policy

## State Changes / User Events
- Notification UI: User clicks confirmation button
- Notification UI: User clicks opt-out button
- User manually updated pref via about:preferences, about:config (and doesn't match prev safed DoH preference) 
- Addon toggles DoH

**Data sent (Possible event states):**
  - loaded
  - enabled
  - disabled
  - manuallyDisabled
  - uninstalled
  - UIOk
  - UIDisabled
  - ~UITimeout~

**Comment by maxxcrawford** [comment]
@nhi-nguyen @wthayer Do we need to remove the UITimeout function?

**Comment by nhi-nguyen** [comment]
@maxxcrawford yes, it should be removed as the doorhanger no longer times out.
